/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsernamesImport } from './routes/usernames'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const UsernamesRoute = UsernamesImport.update({
  path: '/usernames',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/usernames': {
      id: '/usernames'
      path: '/usernames'
      fullPath: '/usernames'
      preLoaderRoute: typeof UsernamesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, UsernamesRoute })

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/usernames"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/usernames": {
      "filePath": "usernames.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
